#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sh -c 'echo "frontend lb-01
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server 481158-web-01 54.196.38.65
    server 481158-web-02 18.234.192.180:80" > /etc/haproxy/haproxy.cfg' 

sudo service haproxy restart
