#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sh -c 'echo "frontend lb-01
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server 481158-web-01 52.23.177.99
    server 481158-web-02 54.144.46.208:80" > /etc/haproxy/haproxy.cfg' 

sudo service haproxy restart
